name: Build Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.6.0

      - name: Install dependencies
        run: npm install --force

      - name: Optimize Angular build configuration
        run: |
          # Disable source maps and increase performance
          sed -i 's/"sourceMap": true/"sourceMap": false/g' angular.json || true

      - name: Build Angular project
        run: |
          npm run build -- --configuration production --aot=false --build-optimizer=false
          
      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
